import '../models/timetable_entry.dart';

const grade11TimetableEntries = <TimetableEntry>[
  TimetableEntry(
    id: 'mon-flag-ceremony',
    title: 'Flag Ceremony',
    dayOfWeek: 1,
    startMinutes: 450,
    endMinutes: 480,
    entryType: TimetableEntryType.activity,
  ),
  TimetableEntry(
    id: 'mon-homeroom',
    title: 'Homeroom Class',
    dayOfWeek: 1,
    startMinutes: 480,
    endMinutes: 530,
  ),
  TimetableEntry(
    id: 'mon-leap-research-consultation',
    title: 'LeAP/Research/Consultation',
    dayOfWeek: 1,
    startMinutes: 530,
    endMinutes: 580,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'mon-stem-research-2',
    title: 'STEM Research 2',
    dayOfWeek: 1,
    startMinutes: 580,
    endMinutes: 630,
  ),
  TimetableEntry(
    id: 'mon-recess',
    title: 'Recess',
    dayOfWeek: 1,
    startMinutes: 630,
    endMinutes: 650,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'mon-science-core',
    title: 'Science Core',
    dayOfWeek: 1,
    startMinutes: 650,
    endMinutes: 750,
  ),
  TimetableEntry(
    id: 'mon-lunch',
    title: 'Lunch Break',
    dayOfWeek: 1,
    startMinutes: 750,
    endMinutes: 810,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'mon-electives',
    title: 'Electives',
    dayOfWeek: 1,
    startMinutes: 810,
    endMinutes: 910,
  ),
  TimetableEntry(
    id: 'mon-english-5',
    title: 'English 5',
    dayOfWeek: 1,
    startMinutes: 910,
    endMinutes: 960,
  ),
  TimetableEntry(
    id: 'mon-consultation-home-bound',
    title: 'Subject Consultation/Home Bound',
    dayOfWeek: 1,
    startMinutes: 960,
    endMinutes: 1020,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'tue-science-core',
    title: 'Science Core',
    dayOfWeek: 2,
    startMinutes: 450,
    endMinutes: 550,
  ),
  TimetableEntry(
    id: 'tue-english-5',
    title: 'English 5',
    dayOfWeek: 2,
    startMinutes: 550,
    endMinutes: 600,
  ),
  TimetableEntry(
    id: 'tue-recess',
    title: 'Recess',
    dayOfWeek: 2,
    startMinutes: 600,
    endMinutes: 620,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'tue-mathematics-5-level-1',
    title: 'Mathematics 5 Level 1',
    dayOfWeek: 2,
    startMinutes: 620,
    endMinutes: 670,
  ),
  TimetableEntry(
    id: 'tue-filipino-5',
    title: 'Filipino 5',
    dayOfWeek: 2,
    startMinutes: 670,
    endMinutes: 720,
  ),
  TimetableEntry(
    id: 'tue-lunch',
    title: 'Lunch Break',
    dayOfWeek: 2,
    startMinutes: 720,
    endMinutes: 780,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'tue-social-science-5',
    title: 'Social Science 5',
    dayOfWeek: 2,
    startMinutes: 780,
    endMinutes: 830,
  ),
  TimetableEntry(
    id: 'tue-electives',
    title: 'Electives',
    dayOfWeek: 2,
    startMinutes: 830,
    endMinutes: 930,
  ),
  TimetableEntry(
    id: 'tue-consultation-home-bound',
    title: 'Subject Consultation/Home Bound',
    dayOfWeek: 2,
    startMinutes: 930,
    endMinutes: 1020,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'wed-mathematics-5-level-1',
    title: 'Mathematics 5 Level 1',
    dayOfWeek: 3,
    startMinutes: 450,
    endMinutes: 500,
  ),
  TimetableEntry(
    id: 'wed-social-science-5',
    title: 'Social Science 5',
    dayOfWeek: 3,
    startMinutes: 500,
    endMinutes: 550,
  ),
  TimetableEntry(
    id: 'wed-leap-research-consultation',
    title: 'LeAP/Research/Consultation',
    dayOfWeek: 3,
    startMinutes: 550,
    endMinutes: 580,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'wed-wellness-break',
    title: 'Wellness Break',
    dayOfWeek: 3,
    startMinutes: 580,
    endMinutes: 600,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'wed-recess',
    title: 'Recess',
    dayOfWeek: 3,
    startMinutes: 600,
    endMinutes: 620,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'wed-stem-research-2',
    title: 'STEM Research 2',
    dayOfWeek: 3,
    startMinutes: 620,
    endMinutes: 670,
  ),
  TimetableEntry(
    id: 'wed-filipino-5',
    title: 'Filipino 5',
    dayOfWeek: 3,
    startMinutes: 670,
    endMinutes: 720,
  ),
  TimetableEntry(
    id: 'wed-lunch',
    title: 'Lunch Break',
    dayOfWeek: 3,
    startMinutes: 720,
    endMinutes: 780,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'wed-leap-advising',
    title: 'LeAP Advising',
    dayOfWeek: 3,
    startMinutes: 780,
    endMinutes: 830,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'wed-electives',
    title: 'Electives',
    dayOfWeek: 3,
    startMinutes: 830,
    endMinutes: 930,
  ),
  TimetableEntry(
    id: 'wed-activity-alp',
    title: 'Activity Proper / ALP',
    dayOfWeek: 3,
    startMinutes: 930,
    endMinutes: 1010,
    entryType: TimetableEntryType.activity,
  ),
  TimetableEntry(
    id: 'wed-consultation-home-bound',
    title: 'Subject Consultation / Home Bound',
    dayOfWeek: 3,
    startMinutes: 1010,
    endMinutes: 1020,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'thu-mathematics-5-level-1',
    title: 'Mathematics 5 Level 1',
    dayOfWeek: 4,
    startMinutes: 450,
    endMinutes: 500,
  ),
  TimetableEntry(
    id: 'thu-social-science-5',
    title: 'Social Science 5',
    dayOfWeek: 4,
    startMinutes: 500,
    endMinutes: 550,
  ),
  TimetableEntry(
    id: 'thu-english-5',
    title: 'English 5',
    dayOfWeek: 4,
    startMinutes: 550,
    endMinutes: 600,
  ),
  TimetableEntry(
    id: 'thu-recess',
    title: 'Recess',
    dayOfWeek: 4,
    startMinutes: 600,
    endMinutes: 620,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'thu-elective-meeting',
    title: 'Elective Meeting',
    dayOfWeek: 4,
    startMinutes: 620,
    endMinutes: 670,
  ),
  TimetableEntry(
    id: 'thu-filipino-5',
    title: 'Filipino 5',
    dayOfWeek: 4,
    startMinutes: 670,
    endMinutes: 720,
  ),
  TimetableEntry(
    id: 'thu-lunch',
    title: 'Lunch Break',
    dayOfWeek: 4,
    startMinutes: 720,
    endMinutes: 780,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'thu-research-laboratory-library',
    title: 'Research Laboratory/Library Time',
    dayOfWeek: 4,
    startMinutes: 780,
    endMinutes: 830,
  ),
  TimetableEntry(
    id: 'thu-electives',
    title: 'Electives',
    dayOfWeek: 4,
    startMinutes: 830,
    endMinutes: 930,
  ),
  TimetableEntry(
    id: 'thu-consultation-home-bound',
    title: 'Subject Consultation / Home Bound',
    dayOfWeek: 4,
    startMinutes: 930,
    endMinutes: 1020,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'fri-science-core',
    title: 'Science Core',
    dayOfWeek: 5,
    startMinutes: 450,
    endMinutes: 500,
  ),
  TimetableEntry(
    id: 'fri-stem-research-2',
    title: 'STEM Research 2',
    dayOfWeek: 5,
    startMinutes: 500,
    endMinutes: 550,
  ),
  TimetableEntry(
    id: 'fri-research-laboratory-consultation',
    title: 'Research Laboratory/Consultation',
    dayOfWeek: 5,
    startMinutes: 550,
    endMinutes: 620,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'fri-elective-meeting',
    title: 'Elective Meeting',
    dayOfWeek: 5,
    startMinutes: 620,
    endMinutes: 670,
  ),
  TimetableEntry(
    id: 'fri-research-laboratory-home-bound',
    title: 'Research Laboratory/Consultation/Home Bound',
    dayOfWeek: 5,
    startMinutes: 670,
    endMinutes: 720,
    entryType: TimetableEntryType.consultation,
  ),
  TimetableEntry(
    id: 'fri-lunch',
    title: 'Lunch Break',
    dayOfWeek: 5,
    startMinutes: 720,
    endMinutes: 780,
    entryType: TimetableEntryType.breakTime,
  ),
  TimetableEntry(
    id: 'fri-electives',
    title: 'Electives',
    dayOfWeek: 5,
    startMinutes: 830,
    endMinutes: 930,
  ),
  TimetableEntry(
    id: 'fri-flag-retreat',
    title: 'Flag Retreat',
    dayOfWeek: 5,
    startMinutes: 920,
    endMinutes: 980,
    entryType: TimetableEntryType.activity,
  ),
  TimetableEntry(
    id: 'fri-consultation-home-bound',
    title: 'Subject Consultation/Home Bound',
    dayOfWeek: 5,
    startMinutes: 980,
    endMinutes: 1020,
    entryType: TimetableEntryType.consultation,
  ),
];
